Allow specifying hosts ad hoc on commandline

diff --git a/tcssh b/tcssh
--- a/tcssh
+++ b/tcssh
@@ -12,13 +12,14 @@ done
 SCRIPT_PATH="$(readlink -f "${SCRIPT_PATH}")"
 
 usage() {
-    echo "Usage: $PROG [options] <cluster>
+    echo "Usage: $PROG [options] [host1 [host2 [host3... ]]]
 
 Cluster ssh using tmux. This differs from other similar scripts by
 allowing the user to define the layout by specifying the number of
-columns instead of just using the tmux \"tiled\" layout. The argument
-<cluster> is either a named cluster or the index corresponding to one
-as provided by the -l/--list option.
+columns instead of just using the tmux \"tiled\" layout. The hosts
+to ssh to can either be explicitly given on the commandline or by
+the cluster index with the -i/--cluster-index option. The cluster
+index can be optained with the -l/--list option.
 
 Options:
 
@@ -32,6 +33,8 @@ Options:
 
   -l, --list           List available clusters.
 
+  -i, --cluster-index  Index of the  desired cluster
+
   -m, --menu           Open tmux menu of clusters (run inside tmux session).
 
   -e, --exclude <host> Host in cluster definition to exclude. Only
@@ -41,26 +44,26 @@ Options:
 "
 }
 function log {
-    if [ "$DEBUG" = "0" ] ; then
+    if [ "$DEBUG" = "0" ]; then
         return
     fi
     logger -t "${PROG}" -- "$@"
 }
 function listClusters {
     local clusters
-    read -ra clusters <<< "$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}'| tr '\n' ' ')"
-    for (( i=0; i < ${#clusters[@]}; i++ )) ; do
-	printf "%2d. %s\n" $((i+1)) "${clusters[$i]}"
+    read -ra clusters <<<"$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}' | tr '\n' ' ')"
+    for ((i = 0; i < ${#clusters[@]}; i++)); do
+        printf "%2d. %s\n" $((i + 1)) "${clusters[$i]}"
     done
 }
 function clusterMenu {
     local clusters
-    read -ra clusters <<< "$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}'| tr '\n' ' ')"
+    read -ra clusters <<<"$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}' | tr '\n' ' ')"
     local args
-    for (( i=0; i < ${#clusters[@]}; i++ )) ; do
+    for ((i = 0; i < ${#clusters[@]}; i++)); do
         args+=("${clusters[$i]}")
         args+=("$i")
-        args+=("run \"${SCRIPT_PATH} $((i+1))\"")
+        args+=("run \"${SCRIPT_PATH} --cluster-index $((i + 1))\"")
     done
     tmux display-menu -T "Cluster SSH" "${args[@]}"
 }
@@ -68,32 +71,32 @@ function clusterMenu {
 function clusterByNumber {
     local i=$1
     local clusters
-    read -ra clusters <<< "$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}'| tr '\n' ' ')"
-    if [[ $i -lt 1 || $i -gt ${#clusters[@]} ]] ; then
-	echo "Invalid cluster index $1." 1>&2
-	echo "None"
+    read -ra clusters <<<"$(grep '^[[:blank:]]*[^[:blank:]#;]' "${CLUSTERFILE}" | awk '{print $1}' | tr '\n' ' ')"
+    if [[ $i -lt 1 || $i -gt ${#clusters[@]} ]]; then
+        echo "Invalid cluster index $1." 1>&2
+        echo "None"
         return 1
     fi
-    echo "${clusters[$((i-1))]}"
+    echo "${clusters[$((i - 1))]}"
     return 0
 }
 
 function calcPercent {
     local i=$1
     local n=$2
-    local num=$((n-i+1))
-    local dom=$((n-i+2))
+    local num=$((n - i + 1))
+    local dom=$((n - i + 2))
     echo "100 * $num / $dom" | bc
 }
 
 function mkSessionName {
     local sn
-    for i in {00..99} ; do
+    for i in {00..99}; do
         sn=tcssh${i}
-        tmux has-session -t "$sn" 2> /dev/null || break
+        tmux has-session -t "$sn" 2>/dev/null || break
         sn=""
     done
-    if [ "$sn" = "" ] ; then
+    if [ "$sn" = "" ]; then
         echo "Error: could not find free session name" 1>&2
         exit 1
     fi
@@ -103,22 +106,22 @@ function mkSessionName {
 function mkWindowIndex {
     # Get list of all the windows in this session
     local warr
-    read -ra warr <<< "$(tmux list-windows | cut -f1 -d: | tr '\n' ' ')"
+    read -ra warr <<<"$(tmux list-windows | cut -f1 -d: | tr '\n' ' ')"
 
     # Loop over possible window indices to find one that is not already
     # used.
-    for i in {1..99} ; do
-	local ok=1
-	for j in "${warr[@]}" ;do
-	    if [ "$i" = "$j" ] ; then
-		ok=0
-		continue
-	    fi
-	done
-	if [ "$ok" = "1" ]; then
-	    echo "$i"
-	    return 0
-	fi
+    for i in {1..99}; do
+        local ok=1
+        for j in "${warr[@]}"; do
+            if [ "$i" = "$j" ]; then
+                ok=0
+                continue
+            fi
+        done
+        if [ "$ok" = "1" ]; then
+            echo "$i"
+            return 0
+        fi
     done
     echo "Can not find free window name." 1>&2
     exit 1
@@ -137,10 +140,10 @@ function readConfig {
 function main {
     log "main()"
     local harr
-    read -ra harr <<< "$1"
+    read -ra harr <<<"$1"
     log "harr =" "${harr[@]}"
     local sshopts
-    read -ra sshopts <<< "$2"
+    read -ra sshopts <<<"$2"
     log "sshopts =" "${sshopts[@]}"
 
     local nc="$NCOL"
@@ -150,132 +153,140 @@ function main {
     local sn=""
 
     # Check if we are already in a tmux session
-    if [ "$TMUX" != "" ] ; then
-       sn=$(tmux display-message -p '#S')
+    if [ "$TMUX" != "" ]; then
+        sn=$(tmux display-message -p '#S')
     fi
     local wi=""
 
-    # Number of panes needs to be >= nhosts and divisible by the number of columns
+    # Number of panes needs to be >= nHOSTS and divisible by the number of columns
     local np
-    [[ $((nhosts%nc)) -eq 0 ]] && np=$nhosts || np=$(echo "$nhosts+$nc-$nhosts%$nc" | bc)
+    [[ $((nhosts % nc)) -eq 0 ]] && np=$nhosts || np=$(echo "$nhosts+$nc-$nhosts%$nc" | bc)
     # Number of rows
     local nr
-    nr=$((np/nc))
+    nr=$((np / nc))
 
     log "nhosts = ${nhosts}, np = ${np}, nc = ${nc}, nr = ${nr}"
     # Loop over the panes
     local tmuxopts tp per
-    for (( col=1; col<=nc ; col++ )) ; do
-	for (( row=1; row<=nr; row++ )) ; do
-	    if [[ $col -eq 1 && $row -eq 1 ]] ; then
-		if [ "$sn" != "" ] ; then
-		    # Use the current session
-		    wi=$(mkWindowIndex)
-		    tmuxopts=("new-window" "-t" "${sn}:${wi}")
-		else
-		    # Make and use a new session
-		    sn=$(mkSessionName)
-		    tmuxopts=("new-session" "-d" "-s" "$sn")
-		fi
-	    elif [ "$col" -eq "1" ] ; then
-		tp=$((row-1))
-		per=$(calcPercent "$row" "$nr")
-		tmuxopts=("split-window" "-t" "${sn}:${wi}.${tp}" "-v" "-l" "${per}%")
-	    else
-		tp=$((row*col-1))
-		per=$(calcPercent "$col" "$nc")
-		tmuxopts=("split-window" "-t" "${sn}:${wi}.${tp}" "-h" "-l" "${per}%")
-	    fi
-	    tmux "${tmuxopts[@]}" ssh "${sshopts[@]}" "${harr[$((hindex++))]}"
-	    if [ "$wi" = "" ] ; then
-		wi=$(tmux display-message -p '#{window_index}')
-	    fi
-	    ((npanes++))
-	    if [ "$npanes" -eq "$nhosts" ] ; then
-		break
-	    fi
-	done
+    for ((col = 1; col <= nc; col++)); do
+        for ((row = 1; row <= nr; row++)); do
+            if [[ $col -eq 1 && $row -eq 1 ]]; then
+                if [ "$sn" != "" ]; then
+                    # Use the current session
+                    wi=$(mkWindowIndex)
+                    tmuxopts=("new-window" "-t" "${sn}:${wi}")
+                else
+                    # Make and use a new session
+                    sn=$(mkSessionName)
+                    tmuxopts=("new-session" "-d" "-s" "$sn")
+                fi
+            elif [ "$col" -eq "1" ]; then
+                tp=$((row - 1))
+                per=$(calcPercent "$row" "$nr")
+                tmuxopts=("split-window" "-t" "${sn}:${wi}.${tp}" "-v" "-l" "${per}%")
+            else
+                tp=$((row * col - 1))
+                per=$(calcPercent "$col" "$nc")
+                tmuxopts=("split-window" "-t" "${sn}:${wi}.${tp}" "-h" "-l" "${per}%")
+            fi
+            tmux "${tmuxopts[@]}" ssh "${sshopts[@]}" "${harr[$((hindex++))]}"
+            if [ "$wi" = "" ]; then
+                wi=$(tmux display-message -p '#{window_index}')
+            fi
+            ((npanes++))
+            if [ "$npanes" -eq "$nHOSTS" ]; then
+                break
+            fi
+        done
     done
 
     tmux rename-window "$CLUSTER"
     tmux set-window-option -t "$sn" synchronize-panes on
 
-    if [ "$TMUX" = "" ] ; then
-	tmux attach -t "$sn"
+    if [ "$TMUX" = "" ]; then
+        tmux attach -t "$sn"
     fi
 }
-
+log "$@"
 SSHOPTS=""
 CLUSTER=""
+HOSTS=""
 readConfig
 declare -a excludes
-while [ "$1" != "" ] ; do
+while [ "$1" != "" ]; do
+    log "\$1 is $1"
     case $1 in
-	-s)
-	    SSHOPTS="$2"
-	    shift
-	    ;;
-	-c)
-	    COLUMNS="$2"
-	    shift
-	    ;;
-	-l|--list)
-	    listClusters
-	    exit 0
-            ;;
-	-m|--menu)
-	    clusterMenu
-	    exit 0
-	    ;;
-	-e|--exclude)
-	    excludes+=("$2")
-	    shift
-	    ;;
-	-d|--debug)
-	    DEBUG=1
-	    ;;
-	-h|--help)
-	    usage
-	    exit 0
-	    ;;
-	*)
-	    CLUSTER=$1
-	    shift
-	    if [[ $CLUSTER =~ ^[0-9]+$ ]] ; then
-		CLUSTER=$(clusterByNumber $((CLUSTER)))
-		if [ "$?" != "0" ] ; then
-		    exit $?
-		fi
-	    fi
-	    ;;
+    -s)
+        SSHOPTS="$2"
+        shift
+        ;;
+    -c)
+        NCOL="$2"
+        log "Setting NCOL to $COLUMNS"
+        shift
+        ;;
+    -l | --list)
+        listClusters
+        exit 0
+        ;;
+    -m | --menu)
+        clusterMenu
+        exit 0
+        ;;
+    -e | --exclude)
+        excludes+=("$2")
+        shift
+        ;;
+    -d | --debug)
+        DEBUG=1
+        ;;
+    -h | --help)
+        usage
+        exit 0
+        ;;
+    -i | --cluster-index)
+        CLUSTER=$2
+        shift
+        if [[ $CLUSTER =~ ^[0-9]+$ ]]; then
+            CLUSTER=$(clusterByNumber $((CLUSTER)))
+            if [ "$?" != "0" ]; then
+                exit $?
+            fi
+        fi
+        ;;
+    *)
+        HOSTS="$HOSTS $1"
+        ;;
     esac
     shift
 done
 
-if [ "$CLUSTER" = "" ] ; then
+if [ "$CLUSTER" = "" ] && [ "$HOSTS" = "" ]; then
     usage
     exit 1
 fi
 
-# Get hosts from cluster name
-hosts="$(sed -n < "${CLUSTERFILE}" "s/^$CLUSTER //p")"
-if [ "$hosts" = "" ] ; then
-    echo "Cluster $CLUSTER not found in $CLUSTERFILE" 1>&2
-    exit 2
+if [ "$HOSTS" = "" ]; then
+    # Get HOSTS from cluster name
+    HOSTS="$(sed -n "s/^$CLUSTER //p" <"${CLUSTERFILE}")"
+    if [ "$HOSTS" = "" ]; then
+        echo "Cluster $CLUSTER not found in $CLUSTERFILE" 1>&2
+        exit 2
+    fi
 fi
 
-# Remove excluded hosts
-wantedhosts=""
-for host in $hosts ; do
+# Remove excluded HOSTS
+WANTEDHOSTS=""
+for host in $HOSTS; do
     exclude=""
-    for exhost in "${excludes[@]}" ; do
-	if [ "${exhost%%.*}" = "${host%%.*}" ] ; then
-	    exclude=1
-	    break
-	fi
+    for exhost in "${excludes[@]}"; do
+        if [ "${exhost%%.*}" = "${host%%.*}" ]; then
+            exclude=1
+            break
+        fi
     done
-    if [ "$exclude" = "" ] ; then
-	wantedhosts="${wantedhosts}${host} "
+    if [ "$exclude" = "" ]; then
+        WANTEDHOSTS="${WANTEDHOSTS}${host} "
     fi
 done
 
