Make error handling a little cleaner.

diff --git a/scripts/tcssh b/scripts/tcssh
--- a/scripts/tcssh
+++ b/scripts/tcssh
@@ -41,7 +41,13 @@ function listClusters {
 function clusterByNumber {
     local i=$1
     read -a CLUSTERS <<< $(grep '^[[:blank:]]*[^[:blank:]#;]' ${CLUSTERFILE} | awk '{print $1}'| tr '\n' ' ')
-    echo ${CLUSTERS[$i]}
+    if [[ $i -lt 1 || $i -gt ${#CLUSTERS[@]} ]] ; then
+	echo "Invalid cluster index $1." 1>&2
+	echo "None"
+        return 1
+    fi
+    echo ${CLUSTERS[$(($i-1))]}
+    return 0
 }
 
 function calcPercent {
@@ -181,7 +187,10 @@ while [ "$1" != "" ] ; do
 	    cluster=$1
 	    shift
 	    if [[ $cluster =~ ^[0-9]+$ ]] ; then
-		cluster=$(clusterByNumber $((--cluster)))
+		cluster=$(clusterByNumber $((cluster)))
+		if [ "$?" != "0" ] ; then
+		    exit $?
+		fi
 	    fi
 	    ;;
     esac
@@ -196,7 +205,7 @@ fi
 # Get hosts from cluster name
 hosts="$(sed -n < "${CLUSTERFILE}" "s/^$cluster //p")"
 if [ "$hosts" = "" ] ; then
-    echo "Cluster $cluster not found in $CLUSTERFILE"
+    echo "Cluster $cluster not found in $CLUSTERFILE" 1>&2
     exit 2
 fi
 
